service:  serverless-example-babel

provider:
  name: aws
  runtime: nodejs8.10

stage: dev
region: us-west-1

functions:
  pokedex:
    handler: handler.pokedex
    events:
      - http:
          path: pokedex
          method: get

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'  # Name of webpack configuration file
    includeModules: true                # Node modules configuration for packaging
    packager: 'npm'                     # Packager that will be used to package your external modules
